<a href="https://colab.research.google.com/github/amirullahadisetya/Pemrograman-Dasar/blob/main/ATS%20KELOMPOK%209.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Fungsi untuk menghitung efisiensi turbin
def hitung_efisiensi(input_energi, output_energi):
    efisiensi = output_energi / input_energi
    return efisiensi

# fungsi dengan input 500 dan output 400
hasil = hitung_efisiensi(500, 400)
print("Nilai efisiensi =", hasil)


Nilai efisiensi = 0.8


Program di atas digunakan untuk menghitung efisiensi turbin. Di dalam program terdapat fungsi bernama hitung_efisiensi yang berisi rumus perbandingan antara energi keluaran dengan energi masukan. Nilai energi masukan yang digunakan adalah 500 dan energi keluarannya 400. Perhitungannya yaitu 400 dibagi 500, sehingga hasilnya 0.8. Nilai tersebut menunjukkan efisiensi turbin sebesar 0.8 atau setara dengan 80%. Hasil akhirnya kemudian ditampilkan menggunakan perintah print.

In [ ]:
# Program Logika if Majemuk/Bertingkat

# Variabel kondisi
tekanan_uap = 160.0              # contoh tekanan dalam psi
status_manual_override = False   # contoh status override (False = tidak aktif)

# Logika if majemuk
if tekanan_uap > 150 and status_manual_override == False:
    print("Katup Terbuka")
else:
    print("Katup Tertutup")


Katup Terbuka


Program ini menggunakan logika if majemuk untuk menentukan apakah katup akan terbuka atau tertutup berdasarkan dua kondisi, yaitu tekanan uap dan status manual override. Nilai tekanan uap yang digunakan adalah 160 psi, dan status override bernilai False (tidak aktif).

Kondisi pada if menyatakan bahwa katup akan terbuka jika tekanan uap lebih dari 150 psi dan status override tidak aktif. Karena tekanan uap bernilai 160 dan override tidak aktif, maka hasil yang ditampilkan adalah:

In [ ]:
# Program menghitung daya listrik

# Diketahui:
tegangan = 220  # dalam Volt
arus = 15       # dalam Ampere

# Rumus daya listrik: P = V × I
daya = tegangan * arus

# Tampilkan hasil
print("Tegangan =", tegangan, "Volt")
print("Arus =", arus, "Ampere")
print("Daya listrik =", daya, "Watt")


Tegangan = 220 Volt
Arus = 15 Ampere
Daya listrik = 3300 Watt


Program ini digunakan untuk menghitung daya listrik berdasarkan rumus: P = V x I. Dimana,

P = daya (watt)
V = tegangan (Volt)
I = arus (ampere)
langkah-langkah dalam program:

V = 220 (nilai tegangan)
I = 15 (nilai arus)
P = V * I (mengalikan tegangan dan arus untuk mendapatkan daya)
print() = menampilkan hasil
hasil yang ditampilkan yaitu:

tegangan (V) = 220 volt arus (I)= 15 ampere daya listrik (P)= 3300 watt

artinya = generator menghasilkan tegangan 220 volt dan arus 15 ampere, maka daya listriknya adalah 3300 watt (3,3 kW).

In [ ]:
# Fungsi untuk menghitung efisiensi termal turbin gas
def hitung_efisiensi_termal(energi_masuk, energi_keluar):
    efisiensi = (energi_keluar / energi_masuk) * 100
    print(f"Efisiensi termal = {efisiensi:.2f}%")

# Contoh pemanggilan fungsi
hitung_efisiensi_termal(1000, 850)


Efisiensi termal = 85.00%


Program ini digunakan untuk menghitung efisiensi termal turbin gas. Nilai energi masuk adalah 1000 dan energi keluar 850. Rumus yang digunakan yaitu (energi_keluar / energi_masuk) * 100. Hasil perhitungan menunjukkan efisiensi termal sebesar 85.00%.

In [ ]:
# Simulasi pengisian tangki bahan bakar

tangki = 0  # mulai dari 0 liter

while tangki <= 100:
    print(f"Isi tangki sekarang: {tangki} liter")

    if tangki == 80:
        print("WARNING: Hampir penuh!")
    elif tangki == 100:
        print("TANGKI PENUH – Pengisian berhenti.")
        break

    tangki += 10  # naikkan 10 liter tiap iterasi


Isi tangki sekarang: 0 liter
Isi tangki sekarang: 10 liter
Isi tangki sekarang: 20 liter
Isi tangki sekarang: 30 liter
Isi tangki sekarang: 40 liter
Isi tangki sekarang: 50 liter
Isi tangki sekarang: 60 liter
Isi tangki sekarang: 70 liter
Isi tangki sekarang: 80 liter
Isi tangki sekarang: 90 liter
Isi tangki sekarang: 100 liter
TANGKI PENUH – Pengisian berhenti.


program ini mensimulasikan pengisian tangki bahan bakar dari 0 liter hingga penuh (100 liter) menggunakan perulangan while.
langkah-langkahnya yaitu:
1. inisialisasi variabel yaitu  tangki = 0 (menandakan tangki mulai dari kosong (0 liter))
2. Perulangan while tangki <= 100: (program akan terus berulang selama nilai tangki masih kurang dari atau sama dengan 100)
3. menampilkan isi tangki saat ini: yaitu = print("mengisi...saat ini:", tangki, "liter")
4. kondisi logika =

*   Jika tangki sudah mencapai 80 liter, tampilkan pesan peringatan:
("WARNING: Hampir penuh!")
*   Jika tangki sudah 100 liter, maka akan menampilkan pesan ("TANGKI PENUH - Pengisian berhenti.) dan hentikan pengisian dengan break:
5. setelah itu menambah isi tangki setiap iterasi (tangki += 10), artinya setiap pengulangan, tangki bertambah 10 liter.

In [3]:
# Fungsi untuk menghitung energi listrik (dalam kWh)
def hitung_energi(daya, waktu):
    energi = (daya * waktu) / 1000  # Rumus: E = P × t
    return energi

# Fungsi untuk menghitung biaya listrik
def hitung_biaya(energi):
    tarif = 1500  # misal tarif listrik per kWh
    return energi * tarif

# Fungsi untuk menampilkan kategori penggunaan energi
def kategori_penggunaan(energi):
    if energi < 10:
        return "Rendah"
    elif energi <= 50:
        return "Sedang"
    else:
        return "Tinggi"

# Program utama
print("PROGRAM ANALISIS ENERGI LISTRIK")

# Menggunakan perulangan while agar user bisa menghitung berulang kali
ulang = "y"
while ulang.lower() == "y":
    total_energi = 0
    jumlah_alat = int(input("Masukkan jumlah alat listrik: "))

    # Menggunakan perulangan for untuk input beberapa alat
    for i in range(jumlah_alat):
        print(f"\nAlat ke-{i+1}")
        nama = input("Nama alat: ")
        daya = float(input("Daya alat (Watt): "))
        waktu = float(input("Lama pemakaian per hari (jam): "))

        energi = hitung_energi(daya, waktu)
        total_energi += energi

        print(f"Energi harian {nama}: {energi:.2f} kWh")

    # Menampilkan hasil total
    print("HASIL ANALISIS")
    print(f"Total Energi Harian: {total_energi:.2f} kWh")
    print(f"Kategori Penggunaan Energi: {kategori_penggunaan(total_energi)}")
    print(f"Perkiraan Biaya Listrik per Hari: Rp{hitung_biaya(total_energi):,.0f}")

    # Tanya apakah ingin mengulang
    ulang = input("\nIngin menghitung lagi? (y/n): ")

print("\nTerima kasih telah menggunakan program ini!")


PROGRAM ANALISIS ENERGI LISTRIK
Masukkan jumlah alat listrik: 2

Alat ke-1
Nama alat: kabel
Daya alat (Watt): 1000
Lama pemakaian per hari (jam): 12
Energi harian kabel: 12.00 kWh

Alat ke-2
Nama alat: stop kontak
Daya alat (Watt): 1800
Lama pemakaian per hari (jam): 24
Energi harian stop kontak: 43.20 kWh
HASIL ANALISIS
Total Energi Harian: 55.20 kWh
Kategori Penggunaan Energi: Tinggi
Perkiraan Biaya Listrik per Hari: Rp82,800

Ingin menghitung lagi? (y/n): n

Terima kasih telah menggunakan program ini!


1.Fungsi (Function)

hitung_energi - menghitung energi berdasarkan daya dan waktu.

hitung_biaya - menghitung biaya berdasarkan energi yang digunakan.

kategori_penggunaan - menentukan apakah penggunaan energi rendah, sedang, atau tinggi.


2.Percabangan (if, elif, else)

Digunakan pada kategori_penggunaan - untuk mengelompokkan tingkat konsumsi energi.


3.Perulangan (for dan while)

-for digunakan untuk menginput data beberapa alat listrik.

-while digunakan agar program bisa dijalankan berulang kali sesuai keinginan pengguna.


Program ini digunakan untuk menghitung energi listrik (kWh) dan biaya listrik, yang merupakan topik penting dalam bidang energi rumah tangga.